from typing import Protocol, Tuple
from cti_rag.contracts import NormalizedArtifact, ObservedRevision, Passage, ProvenanceRef
class EvidenceStore(Protocol):
    def get_revision(self, revision_uid:str)->ObservedRevision|None: ...
    def get_artifact(self, artifact_uid:str)->NormalizedArtifact|None: ...
    def get_passage(self, passage_uid:str)->Passage|None: ...
    def resolve(self, provenance:ProvenanceRef)->bytes|None: ...
    def dependents(self, evidence_uid:str)->Tuple[str,...]: ...
