from typing import Protocol
from cti_rag.contracts import SnapshotManifestRef
from .policy import EffectiveScope
class SnapshotCatalog(Protocol):
    def pin_current(self,scope:EffectiveScope,ttl_seconds:int=30): ...
    def pin_manifest(self,manifest_id:str,scope:EffectiveScope,ttl_seconds:int=30): ...
    def resolve(self,manifest_id:str,scope:EffectiveScope)->SnapshotManifestRef: ...
    def release_lease(self,lease_id:str)->None: ...
